#!/usr/bin/env sh
set -e
SNAZZER_VERSION=0.0.1
SNAZZER_MEAS_LOCK_DIR="/var/lock/snazzer-measure.lock"
SNAZZER_SNAPSHOTZ_PERMS=0700

# For testing
if [ -n "$SNAZZER_DATE" ]; then
    SNAZZER_DATE=$SNAZZER_DATE
elif [ "$SNAZZER_USE_UTC" = "1" ]; then
    SNAZZER_DATE=$(date -u +"%Y-%m-%dT%H%M%SZ")
else
    SNAZZER_DATE=$(date +"%Y-%m-%dT%H%M%S%z")
fi
if [ "$(id -u)" = "0" ]; then
    SUDO=""
else
    SUDO="sudo"
fi
if [ -z "$SNAZZER_MEASUREMENTS_EXCLUDE_FILE" ]; then
    SNAZZER_MEASUREMENTS_EXCLUDE_FILE=".snapshot_measurements.exclude"
fi
# Keep in sync with the POD!
if [ -z "$SNAZZER_SUBVOLS_EXCLUDE_FILE" ]; then
    SNAZZER_SUBVOLS_EXCLUDE_FILE="/etc/snazzer/exclude.patterns"
fi

if ! $SUDO test -e "$SNAZZER_SUBVOLS_EXCLUDE_FILE"; then
    MISSING_SUBVOLS_EXCL_FILE="$SNAZZER_SUBVOLS_EXCLUDE_FILE"
    SNAZZER_SUBVOLS_EXCLUDE_FILE=$(mktemp)
    cat <<HERE > "$SNAZZER_SUBVOLS_EXCLUDE_FILE"
var/cache
var/lib/docker/*
.snapshots
tmp
*backup*
*secret*
HERE
    if [ "$DRY_RUN" = "1" ]; then printf "#"; fi
    cat <<HERE >&2
WARN: $MISSING_SUBVOLS_EXCL_FILE missing, defaulting to $SNAZZER_SUBVOLS_EXCLUDE_FILE:
HERE
    printf "    " >&2
    sed ':a;N;$!ba;s/\n/, /g' "$SNAZZER_SUBVOLS_EXCLUDE_FILE" >&2
fi

# So, mountpoint(1) returns true if the path is a btrfs subvolume root, but we
# want to know if the path is a btrfs *filesystem* root. Hence the df/grep crazy
assert_mountpoint() {
    DIR=$(readlink -f "$1")
    DIR_GREP=$(echo "$DIR" | sed 's|[$.^]|\\&|g')
    if ! mountpoint -q "$DIR" || \
        ! df | grep -c "$DIR_GREP\$" >/dev/null; then
        echo "ERROR: $DIR is not a filesystem mountpoint" >&2
        exit 2
    fi
}

assert_subvolume() {
    DIR=$1
    if ! $SUDO btrfs subvolume show "$DIR" >/dev/null 2>&1; then
        echo "ERROR: $DIR is not a btrfs subvolume" >&2
        exit 3
    fi
}

assert_btrfs_tools() {
    if ! $SUDO btrfs subvolume snapshot --help >/dev/null; then
        echo 'ERROR: btrfs command not found' >&2
        exit 11
    fi
}

glob2grep_file() {
    FILE=$1
    OUT=$(mktemp)

    # first, escape $, . and ^ with a backslash so they're taken literally
    # then, extend * to .* to emulate shell globbing.
    # finally, add ^ and $ to the line ends so the lines are not evaluated as *line*
    sed 's|[$.^]|\\&|g' "$FILE" | sed 's/\*/\.*/g' | sed 's/^/\^/g' | sed 's/$/\$/g' > "$OUT"


    echo "$OUT"
}

# This should only operate on a real mount(8) filesystem mountpoint, so call
# assert_mountpoint before calling list_subvolumes.
list_subvolumes() {
    DIR=$1
    DO_INVERT=$2
    if [ "$DO_INVERT" = "--excluded" ]; then
        GREP="grep"
    else
        GREP="grep -v"
    fi
    if [ "$DIR" != "/" ]; then
            DIR="$DIR/"
    fi
    EXCL_FILE=$(glob2grep_file "$SNAZZER_SUBVOLS_EXCLUDE_FILE")
    $SUDO btrfs subvolume list -t "$DIR" | tail -n+3 | \
        sed 's/^[0-9]*[ \t]*[0-9]*[ \t]*[0-9]*[ \t]*//g' | \
        $GREP -f "$EXCL_FILE" | grep -v '\.snapshotz' | \
        while read -r SUBVOL; do echo "${DIR}$SUBVOL"; done
    rm "$EXCL_FILE"
}

report_subvols_excluded() {
    DIR=$1
    assert_mountpoint "$DIR"
    NUM=$(list_subvolumes "$DIR" --excluded | wc -l)

    if [ "$NUM" != "0" ]; then
        if [ "$DRY_RUN" = "1" ]; then printf "#"; fi
        echo "$NUM subvolumes excluded in $DIR by $SNAZZER_SUBVOLS_EXCLUDE_FILE."
    fi
}

# Get a list of mountpoints from the unique list of devices showing up as
# mounted btrfs filesystems. We don't want to list bind mounts or manually
# mounted subvols (who already have their parent/container filesystems mounted)
# as separate filesystems, that would result in multiple snapshotting of those
# subvols later on.
# SMELL: what if a subvol is mounted some place other than its path name?
list_btrfs_mountpoints() {
    EXCL_FILE=$(glob2grep_file "$SNAZZER_SUBVOLS_EXCLUDE_FILE")
    df -t btrfs 2>/dev/null | tail -n+2 | awk '{ print $1 }' | sort | uniq | \
        while read -r DEV; do df --output=target "$DEV" | tail -n+2 ; done | \
        grep -v '\.snapshotz' | grep -v -f "$EXCL_FILE" || true
    rm "$EXCL_FILE"
}

get_subvol_path() {
    DIR=$1
    UUID=$($SUDO btrfs subvolume show "$DIR" | \
        sed -n 's/^[ \t]*uuid:[ \t]*\(.*\)/\1/p')
    if [ -n "$UUID" ]; then
        $SUDO btrfs subvolume list -u "$DIR" | \
            sed -n "s/^.*$UUID[ \t]*path[ \t]*\\(.*\\)/\\1/p"
    fi
}

# List the excluded subvols relative to DIR
list_subvols() {
    DIR=$1
    SUBVOL_PATH_ESC=$(get_subvol_path "$DIR" | sed -e 's/[]$*.^|[]/\\&/g')
    $SUDO btrfs subvolume list -o "$DIR" | \
        sed -n "s|.*path $SUBVOL_PATH_ESC[/]*\\(.*\\)|\\1|p"
}

assert_missing() {
    THING=$1
    if $SUDO test -e "$THING"; then
        cat <<HERE >&2
ERROR: $THING exists, aborting
HERE
        exit 6
    fi
}

assert_exists() {
    THING=$1
    if ! $SUDO test -e "$THING"; then
        cat <<HERE >&2
ERROR: $THING is missing, aborting
HERE
        exit 4
    fi
}

report_snapshot_dirs() {
    SUBVOL=$1

    if [ "$DO_ACTION" = "snapshot" ] && [ "$SUBVOL" = "/" ]; then
        SUBVOL_MNT=$(df --output=target "$SUBVOL" | tail -n+2)
        for DIR in "/tmp" "/var/tmp" "/var/cache" "/var/log"; do
            DIR_MNT=$(df --output=target "$DIR" | tail -n+2)
            if [ "$DIR_MNT" = "$SUBVOL_MNT" ]; then
                if [ "$DRY_RUN" = "1" ]; then printf "#"; fi
                cat <<HERE
WARN: snapshot of $SUBVOL includes $DIR directory, is this what you wanted?
HERE
            fi
        done
    fi
}

dry_snapshot() {
    SUBVOL=$1
    SUBVOL_ESC=$(echo "$1" | sed "s|'|'\\\\''|g")
    SNAP_DIR_ESC=$(echo "$2" | sed "s|'|'\\\\''|g")
    if [ "$SUBVOL" = "/" ]; then
        EXCL_FILE_ESC="/$SNAZZER_MEASUREMENTS_EXCLUDE_FILE"
    else
        EXCL_FILE_ESC="$SUBVOL_ESC/$SNAZZER_MEASUREMENTS_EXCLUDE_FILE"
    fi

    # The cat | tee below, is in case we're leaning on sudo...
    cat <<CMD
    cat <<EXCL | $SUDO tee '$EXCL_FILE_ESC' >/dev/null
$( list_subvols "$SUBVOL" | sed -e 's|[`$]|\\&|g')
EXCL
    $SUDO btrfs subvolume snapshot -r '$SUBVOL_ESC' '$SNAP_DIR_ESC'
    $SUDO rm '$EXCL_FILE_ESC'
CMD
}

do_snapshot() {
    SUBVOL=$1
    SNAP_DIR=$2
    if [ "$SUBVOL" = "/" ]; then
        EXCL_FILE="/$SNAZZER_MEASUREMENTS_EXCLUDE_FILE"
    else
        EXCL_FILE="$SUBVOL/$SNAZZER_MEASUREMENTS_EXCLUDE_FILE"
    fi

    # The cat | tee below, is in case we're leaning on sudo...
    cat <<EXCL | $SUDO tee "$EXCL_FILE" >/dev/null
$( list_subvols "$SUBVOL" | sed -e 's|[`$]|\\&|g')
EXCL
    $SUDO btrfs subvolume snapshot -r "$SUBVOL" "$SNAP_DIR"
    $SUDO rm "$EXCL_FILE"
}

snapshot() {
    SUBVOL=$1
    assert_subvolume "$SUBVOL"
    assert_missing "$SUBVOL/$SNAZZER_MEASUREMENTS_EXCLUDE_FILE"
    if [ "$SUBVOL" = "/" ]; then
        DEST="/.snapshotz"
    else
        DEST="$SUBVOL/.snapshotz"
    fi
    $SUDO mkdir -p "$DEST" --mode="$SNAZZER_SNAPSHOTZ_PERMS"
    if [ "$DRY_RUN" = "1" ]; then
        dry_snapshot "$SUBVOL" "$DEST/$SNAZZER_DATE"
    else
        do_snapshot "$SUBVOL" "$DEST/$SNAZZER_DATE"
    fi
    assert_missing "$SUBVOL/$SNAZZER_MEASUREMENTS_EXCLUDE_FILE"
}

list_dirs() {
    DIR=$1
    $SUDO ls -F "$DIR" | sed -n 's|^\(.*\)/$|\1|p'
}

# List directories to be pruned under a foo/.snapshotz dir, newline separated.
prune_shotz_dirs() {
    SUBVOL_SHOTZ=$1
    assert_missing "$SUBVOL_SHOTZ/.incomplete"
    $SUDO ls "$SUBVOL_SHOTZ" | snazzer-prune-candidates | \
        while read -r SNAP_NAME; do echo "$SUBVOL_SHOTZ/$SNAP_NAME"; done
}

dry_prune() {
    PRUNE_LIST=$1
    shift
    cat <<CMD
    $(
        IFS=
        echo "$PRUNE_LIST
<<<<EOF>>>>" | while read -r ITEM; do
            if [ "$ITEM" = "<<<<EOF>>>>" ]; then
                echo $SUDO btrfs subvolume delete "$@"
            else
                set -- "$@" "'$(echo "$ITEM" | sed "s|'|'\\\\''|g")'"
            fi
        done
    )
CMD
}

# SMELL: Ugly "while read -r" variable scope limitation work-around. Build up "$@"
# to be used safely w/btrfs. <<<EOF>>> is an unlikely string marking end of list
# at which point we make use of "$@" while it's still in scope.
do_prune() {
    PRUNE_LIST=$1
    shift
    (
        IFS=
        echo "$PRUNE_LIST
<<<<EOF>>>>" | while read -r ITEM; do
            if [ "$ITEM" = "<<<<EOF>>>>" ]; then
                $SUDO btrfs subvolume delete "$@"
            else
                set -- "$@" "$ITEM"
            fi
        done
    )
}

prune() {
    SUBVOL=$1
    if [ "$SUBVOL" = "/" ]; then
        SUBVOL_SHOTZ="/.snapshotz"
    else
        SUBVOL_SHOTZ="$SUBVOL/.snapshotz"
    fi
    assert_subvolume "$SUBVOL"
    assert_exists "$SUBVOL_SHOTZ"
    PRUNE_LIST=$(prune_shotz_dirs "$SUBVOL_SHOTZ")
    NUM_PRUNE=$(echo "$PRUNE_LIST" | grep -c . || true)
    NUM_AVAIL=$(list_dirs "$SUBVOL_SHOTZ" | grep -c . || true )
    if [ "$DRY_RUN" = "1" ]; then printf "#"; fi
    echo "$SUBVOL_SHOTZ: pruning $NUM_PRUNE of $NUM_AVAIL"
    if [ "$DRY_RUN" != "1" ] && [ "$DO_FORCE" != "1" ]; then
        echo "ERROR: --prune expected --force or --dry-run" >&2
        exit 5
    fi
    if [ "$NUM_PRUNE" != "0" ]; then
        if [ -n "$PRUNE_LIST" ]; then
            if [ "$DRY_RUN" = "1" ]; then
                dry_prune "$PRUNE_LIST"
            else
                do_prune "$PRUNE_LIST" | \
                    grep -v 'Transaction commit: none (default)' || true
            fi
        fi
    fi
}

measure_lock() {
    if ! $SUDO test -e "$SNAZZER_MEAS_LOCK_DIR"; then
        true
    elif ! $SUDO test -e "$SNAZZER_MEAS_LOCK_DIR/pid"; then
        echo "ERROR: $SNAZZER_MEAS_LOCK_DIR exists without pidfile 'pid'" >&2
        echo "  Please report this to the author and/or remove the dir" >&2
        exit 7
    else
        OLD_PID=$(cat "$SNAZZER_MEAS_LOCK_DIR/pid")
        if ps --pid="$OLD_PID" >/dev/null; then
            echo "ERROR: A snazzer --measure invocation is already running" >&2
            echo "  $SNAZZER_MEAS_LOCK_DIR/pid is $OLD_PID" >&2
            exit 7
        else
            if [ "$DRY_RUN" = "1" ]; then printf "#"; fi
            cat <<HERE >&2
WARN: Previous snazzer --measure invocation PID $OLD_PID exited ungracefully;
$SNAZZER_MEAS_LOCK_DIR/pid stale
HERE
            $SUDO rm -v "$SNAZZER_MEAS_LOCK_DIR/pid"
            $SUDO rmdir -v "$SNAZZER_MEAS_LOCK_DIR"
        fi
    fi
    $SUDO mkdir "$SNAZZER_MEAS_LOCK_DIR"
    echo "$$" | $SUDO tee "$SNAZZER_MEAS_LOCK_DIR/pid" >/dev/null
}

measure_unlock() {
    $SUDO rm "$SNAZZER_MEAS_LOCK_DIR/pid"
    $SUDO rmdir "$SNAZZER_MEAS_LOCK_DIR"
}

dry_measure() {
    SUBVOL_ESC=$(echo "$1" | sed "s/'/'\\\\''/g")
    REPORT_ESC=$(echo "$2" | sed "s/'/'\\\\''/g")
    FAKEPATH_ESC=$(echo "$3" | sed "s/'/'\\\\''/g")

    cat <<HERE
SNAZZER_SUBVOLS_EXCLUDE_FILE="$SNAZZER_SUBVOLS_EXCLUDE_FILE" \
    snazzer-measure '$SUBVOL_ESC' '$FAKEPATH_ESC' >> '$REPORT_ESC';
HERE
}

do_measure() {
    SUBVOL=$1
    REPORT=$2
    FAKEPATH=$3
    REPORT_TMP=$(mktemp)
    # Avoid putting this in a pipe in case snazzer-measure aborts with error.
    # Also, using a tempfile avoids writing partial measurements to the report.
    SNAZZER_SUBVOLS_EXCLUDE_FILE="$SNAZZER_SUBVOLS_EXCLUDE_FILE" \
        snazzer-measure "$SUBVOL" "$FAKEPATH" > "$REPORT_TMP"
    $SUDO tee -a "$REPORT" <"$REPORT_TMP" >/dev/null
    rm "$REPORT_TMP"
}

# If DO_FORCE=1, measure all snapshots regardless of whether the hostname seems
# to already have made a measurement in the past
measure() {
    SUBVOL=$1
    if [ "$SUBVOL" = "/" ]; then
        SUBVOL_SHOTZ="/.snapshotz"
    else
        SUBVOL_SHOTZ="$SUBVOL/.snapshotz"
    fi
    assert_subvolume "$SUBVOL"
    assert_exists "$SUBVOL_SHOTZ"
    measure_lock
    if ! $SUDO test -e "$SUBVOL_SHOTZ/.measurements"; then
        $SUDO mkdir "$SUBVOL_SHOTZ/.measurements"
    fi
    SNAP_LIST_AVAIL=$($SUDO ls "$SUBVOL_SHOTZ")
    if [ "$DO_FORCE" = "1" ]; then
        SNAP_LIST="$SNAP_LIST_AVAIL"
    else
        # Collect measurements that don't mention our hostname
        SNAP_LIST=$($SUDO grep -rsL "^> on $(hostname) at" \
            "$SUBVOL_SHOTZ/.measurements" | \
            while read -r SNAP_FULLPATH; do basename "$SNAP_FULLPATH"; done)
        # Collect snapshot names without any measurements at all
        # SMELL: What a nasty way to do this. We're trying to limit the number
        # of different things a $SUDO user would need to open up in sudoers, but
        # that's a pretty terribly tedious use-case.
        SNAP_MISSING=$(echo "$SNAP_LIST_AVAIL" | while read -r SNAP_NAME
            do $SUDO test -e \
                "$SUBVOL_SHOTZ/.measurements/$SNAP_NAME" || \
                    echo "$SNAP_NAME"
            done)
        SNAP_LIST=$(echo "$SNAP_LIST"; echo "$SNAP_MISSING")
    fi
    # grep . so we don't count final newline
    NUM_MEAS=$( echo "$SNAP_LIST" | grep -c . || true )
    NUM_AVAIL=$( echo "$SNAP_LIST_AVAIL" | grep -c . || true )
    echo "$SUBVOL: measuring $NUM_MEAS of $NUM_AVAIL"
    if [ -n "$SNAP_LIST" ]; then
        if [ "$DRY_RUN" = "1" ]; then
            echo "$SNAP_LIST" | grep . | while read -r SNAP_NAME; do
                echo "  $SNAP_NAME"
                SNAP_PATH_ESC=$(echo "$SUBVOL_SHOTZ/$SNAP_NAME" | sed "s|'|'\\\\''|g")
                REPORT_PATH_ESC=$(echo "$SUBVOL_SHOTZ/.measurements/$SNAP_NAME" | sed "s|'|'\\\\''|g")
                dry_measure "$SNAP_PATH_ESC" "$REPORT_PATH_ESC" "../$SNAP_NAME"
            done
        else
            echo "$SNAP_LIST" | grep . | while read -r SNAP_NAME; do
                echo "  $SNAP_NAME"
                SNAP_PATH="$SUBVOL_SHOTZ/$SNAP_NAME"
                REPORT_PATH="$SUBVOL_SHOTZ/.measurements/$SNAP_NAME"
                do_measure "$SNAP_PATH" "$REPORT_PATH" "../$SNAP_NAME"
            done
        fi
    fi
    measure_unlock
}

do_multiple() {
    DO_ACTION=$1
    shift
    for SUBVOL in "$@"; do
        # Remove trailing slash
        SUBVOL=$(echo "$SUBVOL" | sed 's|\(.\)/$|\1|g')
        case "$DO_ACTION" in
            'snapshot') snapshot "$SUBVOL"
                        ;;
            'prune')    if ! which snazzer-prune-candidates >/dev/null; then
                            echo 'ERROR: snazzer-prune-candidates not found' >&2
                            exit 10
                        fi
                        prune "$SUBVOL"
                        ;;
            'measure')  if ! which snazzer-measure >/dev/null; then
                            echo 'ERROR: snazzer-measure not found' >&2
                            exit 10
                        fi
                        measure "$SUBVOL"
                        ;;
            'list-subvolumes') echo "$SUBVOL"
                        ;;
            'list-snapshots')
                        if [ "$SUBVOL" = "/" ]; then
                            $SUDO btrfs subvolume list -o "$SUBVOL" | \
                                grep '\.snapshotz' | \
                                sed -n "s|.*path .*\.snapshotz/\(.*\)|/.snapshotz/\1|p"
                        else
                            MOUNTPOINT_ESC=$(echo "$SUBVOL" | \
                                sed 's|[&*$.^\|]|\\&|g')
                            $SUDO btrfs subvolume list -o "$SUBVOL" | \
                                grep '\.snapshotz' | \
                                sed -n "s|^.*path .*\.snapshotz/\(.*\)|$MOUNTPOINT_ESC/\.snapshotz/\1|p"
                        fi
                        ;;
            *) echo "ERROR: invalid cmd '$DO_ACTION'"
               exit 1
               ;;
        esac
    done
    sync
}

DO_ACTION="snapshot"
DO_FORCE=0
DRY_RUN=0
DO_ALL=0

while [ "$(echo "$1" | grep -c "^-" || true)" != 0 ]
do
    case "$1" in
        -v | --version ) echo "$SNAZZER_VERSION"; exit; ;;
        -h | --help ) pod2usage -exit 0 "$0"; exit ;;
             --man ) pod2usage -exit 0 -verbose 3 "$0"; exit ;;
             --man-roff ) pod2man --release=$SNAZZER_VERSION "$0"; exit ;;
             --man-markdown )
             cat <<HERE | perl -Mstrict
if ( eval { require Pod::Markdown; 1; } ) {
    Pod::Markdown->new->filter('$0');
}
else {
    print STDERR "ERROR: --man-markdown requires Pod::Markdown\n\$@\n";
    exit 9;
}
HERE
                 exit ;;
        -p | --prune ) DO_ACTION="prune"; ;;
        -m | --measure ) DO_ACTION="measure"; ;;
             --list-subvolumes ) DO_ACTION="list-subvolumes"; ;;
             --list-snapshots ) DO_ACTION="list-snapshots"; ;;
        -f | --force ) DO_FORCE=1; ;;
        -d | --dry-run ) DRY_RUN=1; ;;
        -a | --all ) DO_ALL=1; ;;
        * ) echo "ERROR: Invalid argument '$1'" >&2 ; exit ;;
    esac
    shift
done

do_mountpoint() {
    MOUNTPOINT=$1
    TMP_EXCL=$2
    TMP_DIRS=$3
    # Remove trailing slash
    if [ "$MOUNTPOINT" != "/" ]; then
        MOUNTPOINT=$(echo "$MOUNTPOINT" | sed 's|/$||g')
    fi
    do_multiple "$DO_ACTION" "$MOUNTPOINT"
    report_subvols_excluded "$MOUNTPOINT" >> "$TMP_EXCL"
    report_snapshot_dirs "$MOUNTPOINT" >> "$TMP_DIRS"
    assert_mountpoint "$MOUNTPOINT"
    list_subvolumes "$MOUNTPOINT" | {
        while read -r SUBVOL; do
            do_multiple "$DO_ACTION" "$SUBVOL"
            report_snapshot_dirs "$SUBVOL" >> "$TMP_DIRS"
        done
    }
}

do_mountpoints() {
    TMP_EXCL=$(mktemp)
    TMP_DIRS=$(mktemp)
    if [ "$#" = 0 ]; then
        list_btrfs_mountpoints | {
            while read -r MOUNTPOINT; do
                do_mountpoint "$MOUNTPOINT" "$TMP_EXCL" "$TMP_DIRS"
            done
        }
    else
        for MOUNTPOINT in "$@"; do
            do_mountpoint "$MOUNTPOINT" "$TMP_EXCL" "$TMP_DIRS"
        done
    fi
    if [ -s "$TMP_EXCL" ]; then
        echo "" >&2
        cat "$TMP_EXCL" >&2
    fi
    if [ -s "$TMP_DIRS" ]; then
        echo ""
        cat "$TMP_DIRS"
    fi
    rm "$TMP_EXCL"
    rm "$TMP_DIRS"
}

if [ -z "$1" ] && [ "$DO_ALL" != "1" ]; then
    pod2usage -exit 0 "$0"
    echo "ERROR: Missing argument" >&2
    exit 1
elif [ "$DO_FORCE" = "1" ] && [ "$DRY_RUN" = "1" ]; then
    pod2usage -exit 0 "$0"
    echo "ERROR: --force and --dry-run are incompatible" >&2
    exit 1
elif [ "$DO_ALL" = "1" ]; then
    assert_btrfs_tools
    if [ -z "$1" ]; then
        do_mountpoints
    elif [ -n "$1" ] && [ -z "$2" ]; then
        do_mountpoints "$1"
    else
        pod2usage -exit 0 "$0"
        echo "ERROR: Extraneous argument '$2'" >&2
        exit 1
    fi
else
    assert_btrfs_tools
    do_multiple "$DO_ACTION" "$@"
fi
if [ -n "$MISSING_SUBVOLS_EXCL_FILE" ]; then
    rm "$SNAZZER_SUBVOLS_EXCLUDE_FILE";
fi

<<__DNE__
__END__
=head1 NAME

snazzer - create read-only C</subvol/.snapshotz/[isodate]> btrfs snapshots,
offers snapshot pruning and measurement

=head1 SYNOPSIS

  snazzer [--prune|--measure [--force ]] [--dry-run] --all

  snazzer [--prune|--measure [--force ]] [--dry-run] --all [mountpoint]

  snazzer [--prune|--measure [--force ]] [--dry-run] subvol1 [subvol2 [...]]

=head1 DESCRIPTION

Examples:

Snapshot all non-excluded subvols on all mounted btrfs filesystems:

  snazzer --all

Prune all non-excluded subvols on all mounted btrfs filesystems:

  snazzer --prune --force --all

Append output of B<snazzer-measure> to
C</path/to/subvol/.snapshotz/.measurements/[isodate]> for all snapshots of all
subvolumes on all mounted btrfs filesytems (slow!):

  snazzer --measure --force --all

As above, skipping snapshots already measured by this host (recommended):

  snazzer --measure --all

Print rather than execute commands for snapshotting all non-excluded subvols for
the filesystem mounted at /mnt (including /mnt itself):

  snazzer --dry-run --all /mnt

Prune only the explicitly named subvols at /srv, /var/log and root:

  snazzer --prune /srv /var/log /

=head1 OPTIONS

=over

=item B<--all> B<[mountpoint]>: act on all subvolumes under mountpoint. If
mountpoint is omitted, B<snazzer> acts on all mounted btrfs filesystems.

=item B<--prune>: delete rather than create snapshots. Exactly which are no
longer needed is B<snazzer-prune-candidates>'s role, documented separately

=item B<--measure>: append output of B<snazzer-measure> to
C</path/to/subvol/.snapshotz/.measurements/[isodate]> By default, only snapshots
which haven't been measured by this hostname are updated - use B<--force> to
measure all snapshots

=item B<--force>: required for B<--prune> to carry out any pruning operation.
For B<--measure>, this switch overrides the default behaviour of skipping
snapshots already measured by current hostname

=item B<--list-subvolumes>: list subvolumes that would be acted on

=item B<--list-snapshots>: list snapshots under subvolumes as above

=item B<--dry-run>: print rather than execute commands that would be run

=item B<--help>: Brief help message

=item B<--version>: Print version

=item B<--man>: Full documentation

=item B<--man-roff>: Full documentation as *roff output, Eg:

    snazzer --man-roff | nroff -man

=item B<--man-markdown>: Full documentation as markdown output, Eg:

    snazzer --man-markdown > snazzer-manpage.md

=back

=head1 ENVIRONMENT

=over

=item * SNAZZER_SUBVOLS_EXCLUDE_FILE

Filename of newline separated list of shell glob patterns of subvolume pathnames
which should be excluded from C<snazzer --all> invocations; compatible with
C<--exclude-from> for B<du> and B<tar>.  Examples of subvolume patterns to
exclude from regular snapshotting: *secret*, var/cache, var/lib/docker/*,
.snapshots. The patterns are matched against subvolumes as listed by
C<btrfs subvolume list <path>>, without a leading /.
Note that   B<NOTE:> C<.snapshotz> is always excluded.
Default:

  SNAZZER_SUBVOLS_EXCLUDE_FILE="/etc/snazzer/exclude.patterns"

=item * SNAZZER_USE_UTC=1

For snapshot naming and B<snazzer-measure> output use UTC times of the form
C<YYYY-MM-DDTHHMMSSZ> instead of local time+offset C<YYYY-MM-DDTHHMMSS+hhmm>

=back

=head1 BUGS AND LIMITATIONS

=over

=item * Snapshot naming

A choice has been made to mint a single datetime string which is used for all
snapshot names in a given B<snazzer> snapshot invocation, regardless of how long
or at which exact time the snapshotting process takes place for each subvolume.
This makes for consistency across all subvolumes and filesystems, so that
identifying which snapshots were part of a given snapshotting run is possible.
If the actual datetime of the snapshot event is important to you, this is
available from the C<btrfs subvolume show> command.

=item * SNAZZER_SUBVOLS_EXCLUDE_FILE is used with grep -f

A minimal (possibly buggy/incomplete) attempt is made to convert the shell glob
patterns in this file to a regex suitable for grep -f. The assumption is that
the exclude patterns file should only contain "boring" paths. Obvious regex
characters are escaped, however there are likely hostile path glob patterns
which will break things.

=item * .snapshot_measurements.exclude is a work-around to the btrfs atime bug

Snapshots may include empty directories under which some other subvol may have
existed in the original, snapshotted subvolume. However, btrfs has a bug where
these empty directories behave differently to empty directories created with
C<mkdir>: atimes always return with the current local time, which is obvioulsy
different from one second to the next. So we have no hope of creating
reproducible shasums or PGP signatures unless those directories are excluded
from our measurements of the snapshot. See also: 
L<https://bugzilla.kernel.org/show_bug.cgi?id=95201>

=back

=head1 EXIT STATUS

B<snazzer> will abort with an error message printed to STDERR and non-zero exit
status under the following conditions:

=over

=item 1. invalid arguments

=item 2. path is not a filesystem mountpoint

=item 3. one or more paths were not btrfs subvolumes

=item 4. prune expected /path/to/subvol/.snapshotz directory which was missing

=item 5. prune expected --dry-run or --force

=item 6. tried to write a .snapshot_measurements.exclude file in the snapshot
root, but it already exists in the current subvolume

=item 7. tried to perform snapshot measurements while existing measurements are
already in progress, check lock dir at /var/run/snazzer-measure.lock

=item 9. tried to display man page with a formatter which is not installed

=item 10. missing C<snazzer-measure> or C<snazzer-prune-candidates> from PATH

=item 11. missing C<btrfs> command from PATH

=back

=head1 SEE ALSO

snazzer-measure, snazzer-prune-candidates, snazzer-receive

=head1 AUTHOR

Snazzer Authors are listed in the AUTHORS.md file in the root of this
distribution. See https://github.com/csirac2/snazzer for more information.
NOTE: Please extend that file, not this notice.

=head1 LICENSE AND COPYRIGHT

Copyright (C) 2015-2016, Snazzer Authors All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
=cut
__DNE__
